-- GearBeat seed placeholder
-- Intentionally empty.
-- Historical seed SQL was archived to:
-- docs/sql-drafts/GEARBEAT_LEGACY_SEED_ARCHIVE_DO_NOT_RUN.sql.txt
--
-- Reason:
-- Supabase Preview runs supabase/seed.sql after migrations.
-- The old seed contained generated-column expressions that can fail preview builds.
-- Do not place schema DDL, generated columns, demo users, fake studios, fake rewards,
-- or production-like seed data in this file.
